<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>SharedCode.Data.Tests</AssemblyName>
        <Description>A library of tests for the SharedCode.Data library.</Description>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);AD0001</NoWarn>
        <OutputType>Exe</OutputType>
        <RootNamespace>SharedCode.Data.Tests</RootNamespace>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);AD0001</WarningsNotAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="GCop.All.Common">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\SharedCode.Data\Data.csproj" />
    </ItemGroup>
</Project>
