name: .NET

on:
  push:
    branches: [ main ]
    tags:
    - "**"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Push Core
      run: dotnet nuget push SharedCode.Core/*.?nupkg --source nuget.org --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
    - name: Push Data
      run: dotnet nuget push SharedCode.Data/*.?nupkg --source nuget.org --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
    - name: Push Data.EntityFramework
      run: dotnet nuget push SharedCode.Data.EntityFramework/*.?nupkg --source nuget.org --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
    - name: Push DependencyInjection
      run: dotnet nuget push SharedCode.DependencyInjection/*.?nupkg --source nuget.org --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
    - name: Push Windows.WPF
      run: dotnet nuget push SharedCode.Windows.WPF/*.?nupkg --source nuget.org --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
