name: .NET

on:
  push:
    branches: [ main ]
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release /p:Version=${VERSION}

    - name: Push
      run: dotnet nuget push SharedCode.Core/SharedCode.Core.*nupkg --skip-duplicate --api-key ${secrets.NUGET_API_KEY}

    - name: Publish SharedCode.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: SharedCode.Core/Core.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish SharedCode.Data
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: SharedCode.Data/Data.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish SharedCode.Data.EntityFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: SharedCode.Data.EntityFramework/Data.EntityFramework.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish SharedCode.DependencyInjection
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: SharedCode.DependencyInjection/DependencyInjection.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish SharedCode.Windows.WPF
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: SharedCode.Windows.WPF/Windows.WPF.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
